### ISSUE TITLE
Building FEniCS 2024

### ISSUE THREAD

**Issue by AnoopRKulkarni** [finsberg/ldrb#112]
Hi,

I already have PETSc installed as part of openCARP installation on my machine. Looks like just doing "sudo apt install fenicsx" does not work because of existing PETSc installation. Says "import dolfinx" - module not found!

I was exploring an option of building FEniCS from sources. However the instructions are not very clear. And also how much of a change do I need to make to "ldrb", because it uses the "dolfin" and not "dolfinx" interface.

Any advice is highly appreciated.

~anoop

**Comment by finsberg** [comment]
Hi @AnoopRKulkarni, there is a new package of ldrb for dolfinx that you can find here: https://github.com/finsberg/fenicsx-ldrb/

**Comment by AnoopRKulkarni** [comment]
> Hi @AnoopRKulkarni, there is a new package of ldrb for dolfinx that you can find here: https://github.com/finsberg/fenicsx-ldrb/

Brilliant! Thanks so much!

**Comment by AnoopRKulkarni** [comment]
I tried running the sample code. When I try to import ldrb, I get the following error

ModuleNotFoundError: No module named 'adios2'

If I do "pip install adios2", it messes up dolfinx import

~anoop

**Comment by finsberg** [comment]
@AnoopRKulkarni Could you please open the issue in the correct repository, and also explain how you installed FEniCSx and what OS you are using. Thanks

**Comment by AnoopRKulkarni** [comment]
Will do. Apologies..
