### ISSUE TITLE
Can I use your code to generate fiber discrete fields via an inp file

### ISSUE THREAD

**Issue by vensun41** [finsberg/ldrb#115]
Thank you very much for sharing. Please forgive me for being a newbie. I would like to ask if I can use your code to generate discrete fields for abaqus fibers based on an inp file.

**Comment by finsberg** [comment]
Hi! No problem. I have no experience with abaqus, and no idea what an inp file is, sorry. You could save the fibers in xdmf, open them in Paraview, and perhaps it is possible to export to the format you want?

**Comment by finsberg** [comment]
You could also try to convert your mesh to XDMF first with [`meshio`](https://github.com/nschloe/meshio)
