### ISSUE TITLE
Replication results of paper with benchmark problem3 

### ISSUE THREAD

**Issue by jingbinzhao415** [finsberg/ldrb#30]
Hi Finsberg,

I cannot get the same results by Pulse demo code<BenchMarkProblem3> when I did the replication of the paper <Verification of cardiac mechanics software: benchmark problems and solutions for testing active and passive material behaviour>.
Here is the fiber orientations I get on the top layer.

f0: 
![image](https://user-images.githubusercontent.com/93218388/164084252-b1c61d05-da52-4c75-98f5-2735156263c8.png)

n0:
![image](https://user-images.githubusercontent.com/93218388/164084319-d9e2449e-df9b-4141-a0d2-b713b9c4eabf.png)

s0:
![image](https://user-images.githubusercontent.com/93218388/164084428-2fae719c-d55a-41e1-beed-d937025d0a36.png)

Looking forward to hearing from you.

Thanks,
Jingbin

**Comment by finsberg** [comment]
Dear Jingbin, 

Thanks for your issue.

Could you please be a bit more specific? 
What code did you run to generate these results?
What did you expect, or what does not look correct (which demo are you pointing to)?
Which version of `ldrb` did you use?
Which version of `FEniCS` did you use?

Henrik

**Comment by jingbinzhao415** [comment]
Hi Finsberg,

I used benchmarkproblem3 code.
The longitudinal position of endo_apex and epi_apex from the demo code is: 
![image](https://user-images.githubusercontent.com/93218388/164086181-2c43f925-40e7-4385-aa50-2ecb259ad712.png)

which are different with paper:
![image](https://user-images.githubusercontent.com/93218388/164086047-6a0ca8bb-bf50-40de-aba0-bb7447b15a96.png)

The Idrb version is: 2022.1.0
The fenics version is:  
fenics-dijitso                2019.1.0
fenics-dolfin                 2019.2.0.dev0
fenics-ffc                    2019.1.0.post0
fenics-fiat                   2019.1.0
fenics-plotly                 0.1.6
fenics-pulse                  2022.1.1
fenics-ufl                    2019.1.0

**Comment by finsberg** [comment]
I guess this should be an issue in `pulse` then, and not `ldrb`, or am I missing something? The fibers used for the benchmark problem is not generated using `ldrb`. They are computed analytically.

**Comment by jingbinzhao415** [comment]
If the fiber in benchmark problem is not generated by Idrb, then the issue is from Pulse. Could you please check the position of the endo apex and epi apex of benchmarkProblem3 in Pulse? Thanks in advance for your assistance!

**Comment by finsberg** [comment]
@jingbinzhao415 Is it OK if we close this. I just submitted a bug fix. Perhaps this also solves your problem?

**Comment by jingbinzhao415** [comment]
Thanks for your reply and it worked properly very well, you can close this. Thank you again!
