### ISSUE TITLE
Functions missing

### ISSUE THREAD

**Issue by jtgreen** [finsberg/ldrb#63]
gmsh2dolfin has disappeared and the demo strocchi is broken.

**Comment by finsberg** [comment]
Thanks for letting me know. This function is moved here: https://github.com/ComputationalPhysiology/cardiac_geometries/blob/main/src/cardiac_geometries/dolfin_utils.py#L46
Would you like to try to fix this with a pull request?

**Comment by jtgreen** [comment]
Absolutely, gimme a few.
