### ISSUE TITLE
Run demos

### ISSUE THREAD

**Issue by correctanswerdd** [finsberg/ldrb#86]
Hi Finsberg,

Thank you for your work on ldrb! I'm currently trying to run the demos you've provided, such as [demo_lv.py](https://github.com/finsberg/ldrb/blob/main/demos/demo_lv.py) and [demo_biv.py](https://github.com/finsberg/ldrb/blob/main/demos/demo_biv.py). Unfortunately, I'm encountering an error message: `UFLValueError: Invalid type conversion: v_1 cannot be converted to any UFL type.`

To give you more context, I'm using the `simcardems` Docker environment and have installed `ldrb` and `ufl` using pip. I've followed the instructions as closely as possible, but I'm still encountering this issue.

I'd greatly appreciate any suggestions or guidance you can provide to help resolve this problem. Thanks in advance for your assistance!

Best regards,

**Comment by finsberg** [comment]
Hi!

I accidentally bumped the version of the base docker image to a version of fenics that uses `ufl_legacy` rather than `ufl` (see https://fenicsproject.discourse.group/t/announcement-ufl-legacy-and-legacy-dolfin/11583).
I will create a new image for `simcardems` with the "old" `ufl` until I have migrated to `ufl_legacy` for all my repos. 
Will push out a new image now so should be ready in an hour or so.

**Comment by finsberg** [comment]
New image will be created here: https://github.com/ComputationalPhysiology/simcardems/actions/runs/6285808159

**Comment by correctanswerdd** [comment]
> New image will be created here: https://github.com/ComputationalPhysiology/simcardems/actions/runs/6285808159

Thanks Dr. Finsberg! I tried the new image, but when I want to run [simple_demo.py](https://github.com/ComputationalPhysiology/simcardems/blob/main/demos/simple_demo.py) in `simcardems` it still gets the error: 
```
Traceback (most recent call last):
  File "/app/simcardems/demos/simple_demo.py", line 9, in <module>
    import simcardems
  File "/usr/lib/python3/dist-packages/simcardems/__init__.py", line 6, in <module>
    import pulse as _pulse
  File "/usr/lib/python3/dist-packages/pulse/__init__.py", line 61, in <module>
    from . import dolfin_utils
  File "/usr/lib/python3/dist-packages/pulse/dolfin_utils.py", line 3, in <module>
    import ufl
ModuleNotFoundError: No module named 'ufl'
```

**Comment by finsberg** [comment]
@correctanswerdd I have now updated all my libraries to support both `ufl` and `ufl_legacy`. Could you try again with the latest image?
