### ISSUE TITLE
Fiber generation problem

### ISSUE THREAD

**Issue by wang-hairui** [finsberg/ldrb#88]
Hi，Dr. Finsberg!

​	Thank you very much for providing the Python implementation of LDRB. I have a question and would like to consult you.

​	When running the example "Life X - idealized_LV" (https://finsberg.github.io/ldrb/demo_lifex_idealized_LV.html), I noticed that the number of generated fiber vectors corresponds to the number of points in the mesh (read from the stored fiber.xdmf using meshio, where fibers are also stored in ‘point_data’). Can I understand that the algorithm you provided assigns a fiber direction to each point in the mesh?

​	If I want to assign a specific fiber direction to each tetrahedron in the mesh, how should I proceed? Do you have any suggestions or examples I can refer to?

**Comment by finsberg** [comment]
If you use the fiber space "P_1" it will assign a fiber direction to each point in the mesh. To assign one fiber direction to each tetrahedron, you need to use "DG_0" space

**Comment by wang-hairui** [comment]
Thank you very much for your response！！This answer solved my problem. 
May you provide some links or documents for me to further understand the other available options for the "fiber_space"?

**Comment by wang-hairui** [comment]
I will carefully read these references. Thanks again for your response !!!
