### ISSUE TITLE
Introducing optional lists for markers

### ISSUE THREAD

**Issue by Reidmen** [finsberg/ldrb#98]
In my current pipeline, I'm in the situation that the markers are not only specified with a single integer, instead they are composed by two (or more).

Is there any desire to allow list of makers to be specified instead of a single value (int). e.g. below

```python
markers = dict(base=[10, 20], rv=30, lv=40, epi=50)
```

PD. I've implemented a working version for this case.

**Comment by finsberg** [comment]
I think this is a great idea! Feel free to submit a PR
